### ISSUE TITLE
物流基站无法放置

### ISSUE THREAD

**Issue by WIYouXi666** [fqy2009/BetterLogisticsNetwork#1]
时间  2/19  09:50:44
pe版本 145.1/146 爆炸

> NoClassDefFoundError: 'Failed resolution of: Ljava/lang/Iterable$-CC;'
Seq.forEach: 0
UnitCargoStation$UnitCargoStationBuild.updateTile: 128
Building.update: 18
EntityGroup.update: 2
Groups.update: 5
Logic.update: 45
ApplicationCore.update: 2
ClientLauncher.update: 20
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1582
GLSurfaceView$GLThread.run: 1272
> ClassNotFound: 'java.lang.Iterable$-CC'
Seq.forEach: 0
UnitCargoStation$UnitCargoStationBuild.updateTile: 128
Building.update: 18
EntityGroup.update: 2
Groups.update: 5
Logic.update: 45
ApplicationCore.update: 2
ClientLauncher.update: 20
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1582
GLSurfaceView$GLThread.run: 1272

**Comment by fqyNOPE** [comment]
由于安卓系统不支持forEach导致的崩溃，新版本已经解决。
